### ISSUE TITLE
An improved greedy solution can perform equally well in the example

### ISSUE THREAD

**Issue by tuliren** [rideOS/examples#1]
In the scooter example, the fleet planner solution performs much better than the greedy solution. However, a closer look at the greedy solution reveals that in this solution, the Mission Courier is doing the majority of the work, resulting in an extremely unbalanced workload between the two couriers.

If the workload is evenly distributed, the greedy solution can do equally well, or even better than the current fleet planner. Here is the comparison of the fleet planner vs an improved greedy solution. When I ran the tests around 1:00 am, the latter can outperform the former most of the time.

| Mission Courier Capacity | Richmond Courier Capacity | Fleet Planner Solution (minutes) | Improved Greedy Solution (minutes)
| ---- | ---- | ---- | ---- |
| 3 | 3 | 262 ✅ | 269 |
| 3 | 5 | 259 | 214 ✅ |
| 3 | 7 | 237 | 202 ✅ |
| 5 | 3 | 240 | 206 ✅ |
| 5 | 5 | 212 | 192 ✅ |
| 5 | 7 | 179 | 170 ✅ |
| 7 | 3 | 224 | 187 ✅ |
| 7 | 5 | 192 | 149 ✅ |
| 7 | 7 | 193 | 151 ✅ |

It is possible that at 1:00 am, there is no traffic at all, which significantly changes the results. However, since the workload is more balanced in the improved greedy solution, it makes sense that it is superior than the naive greedy solution, and therefore it is a more fair comparison.

I know that this scooter example is an oversimplification of actual use cases. However, to demonstrate the true power of the fleet planner, a more sophisticated example should be given, in which the fleet planner can more consistently beat the improved greedy solution.

Relevant code change is shown in #2.

**Comment by chrismrideos** [comment]
Closing per comment in #2
